Atalov S. (TSI AUCA)

# SQLite and Python Exercises for an E-Commerce Database

---

Objective: Practice SQL using SQLite in Python by creating and manipulating an e-commerce database.

Instructions: For these exercises, you will use the sqlite3 module in Python to interact with an SQLite database. Each exercise builds upon the previous one. Ensure you save your progress, as later exercises depend on the previous ones.

### Exercise 1: Setting Up the Database

	•	Task: Create a new SQLite database named ecommerce.db.
	•	Create a table named Customers with the following columns:
	•	CustomerID (INTEGER, Primary Key, Auto-increment)
	•	FirstName (TEXT)
	•	LastName (TEXT)
	•	Email (TEXT)
	•	JoinDate (DATE)

Hint: Use sqlite3.connect() to create a connection and cursor.execute() to run SQL commands.

Here’s a small example to help you get started with Exercise 1:


```python
import sqlite3

# Connect to the database (or create it)
conn = sqlite3.connect('ecommerce.db')
cursor = conn.cursor()

# Create the Customers table
cursor.execute('''
CREATE TABLE IF NOT EXISTS Customers (
    CustomerID INTEGER PRIMARY KEY AUTOINCREMENT,
    FirstName TEXT,
    LastName TEXT,
    Email TEXT,
    JoinDate DATE
)
''')

# Commit changes and close the connection
conn.commit()
conn.close()

```

Good luck, and have fun exploring SQLite with Python!

In [34]:
import sqlite3
conn = sqlite3.connect('ecommerce.db')
cursor = conn.cursor()
cursor.execute('''
CREATE TABLE IF NOT EXISTS Customers (
    CustomerID INTEGER PRIMARY KEY AUTOINCREMENT,
    FirstName TEXT,
    LastName TEXT,
    Email TEXT,
    JoinDate DATE
)
''')
conn.commit()

### Exercise 2: Adding Data to the Customers Table

	•	Task: Insert at least five records into the Customers table with fictional customer data.

Hint: Use INSERT INTO statements and consider using Python variables for dynamic data.

In [35]:
insert_data_query = '''
INSERT INTO Customers (FirstName, LastName, Email, JoinDate) VALUES (?, ?, ?, ?)
'''
customer_data =[('Shakil','Onlil','shaccc@gmail.com', '2023.05.12'),
                ('SSkibidi','Toilet','skibidi@gmail.com', '2021-12-01'),
                ('Don','Donov','dondon@gmail.com', '2024-07-01'),
               ('Clu','Wave','Cluwave@gmail.com', '2020-03-01'),
               ('Scan','Dall','Scandall@gmail.com', '2022-01-01')]
cursor.executemany(insert_data_query, customer_data)
conn.commit()

In [36]:
cursor.execute('SELECT * FROM Customers')

all_cus = cursor.fetchall()
all_cus

[(1, 'Shakil', 'Onlil', 'shaccc@gmail.com', '2023.05.12'),
 (2, 'SSkibidi', 'Toilet', 'skibidi@gmail.com', '2021-12-01'),
 (3, 'Don', 'Donov', 'dondon@gmail.com', '2024-07-01'),
 (4, 'Clu', 'Wave', 'Cluwave@gmail.com', '2020-03-01'),
 (5, 'Scan', 'Dall', 'Scandall@gmail.com', '2022-01-01')]

In [33]:
# drop_customers_table = '''
# DROP TABLE IF EXISTS Customers
# '''

# cursor.execute(drop_customers_table)
# conn.commit()

### Exercise 3: Creating More Tables

Create a table named Products with the following columns:

	•	ProductID (INTEGER, Primary Key, Auto-increment)
	•	ProductName (TEXT)
	•	Price (REAL)
	•	Stock (INTEGER)

Create a table named Orders with the following columns:

	•	OrderID (INTEGER, Primary Key, Auto-increment)
	•	CustomerID (INTEGER, Foreign Key referencing Customers(CustomerID))
	•	OrderDate (DATE)


Create a table named OrderDetails with the following columns:

	•	OrderDetailID (INTEGER, Primary Key, Auto-increment)
	•	OrderID (INTEGER, Foreign Key referencing Orders(OrderID))
	•	ProductID (INTEGER, Foreign Key referencing Products(ProductID))
	•	Quantity (INTEGER)

Hint: Remember to enforce foreign key constraints by setting FOREIGN KEY relationships.

In [37]:
create_products_table= '''
CREATE TABLE IF NOT EXISTS Products (
    ProductID INTEGER PRIMARY KEY AUTOINCREMENT,
    ProductName TEXT,
    Price REAL,
    Stock INTEGER
)
'''
conn.execute(create_products_table)
conn.commit()
create_orders_table = '''
        CREATE TABLE IF NOT EXISTS Orders (
    OrderID INTEGER PRIMARY KEY AUTOINCREMENT,
    CustomerID INTEGER, 
    OrderDate DATE,
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
    
)
'''
conn.execute(create_orders_table)
conn.commit()
create_orderdetails_table = '''
CREATE TABLE IF NOT EXISTS OrderDetails (
    OrderDetailID INTEGER PRIMARY KEY AUTOINCREMENT,
    OrderID INTEGER, 
    Quantity INTEGER,
    ProductID INTEGER,  
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
    FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
)
'''
conn.execute(create_orderdetails_table)
conn.commit()

### Exercise 4: Populating the Products Table

	•	Task: Insert at least five products into the Products table with fictional product data.

In [38]:
insert_products_query = '''
    INSERT INTO Products (ProductName,Price,Stock) VALUES(?,?,?)
'''
products_data = [
    ('Laptop', 999.99, 10),
    ('Smartphone', 699.99, 25),
    ('Headphones', 199.99, 50),
    ('Monitor', 249.99, 15),
    ('Keyboard', 49.99, 100)
]
cursor.executemany(insert_products_query,products_data)
conn.commit()

### Exercise 5: Populating the Orders and OrderDetails Tables

	•	Task: Create at least three orders, each associated with a different customer from the Customers table.
	•	For each order, add at least two products from the Products table into the OrderDetails table with quantities.

Hint: Ensure that CustomerID in Orders matches an existing customer.

In [39]:
orders_data = [
    (1, '2024-10-01'), 
    (2, '2024-10-02'), 
    (3, '2024-10-03') 
]

insert_orders_query = '''
INSERT INTO Orders (CustomerID, OrderDate) VALUES (?, ?)
'''

cursor.executemany(insert_orders_query, orders_data)
conn.commit()

# Step 2: Insert OrderDetails
order_details_data = [
    (1, 1, 2),  # OrderID 1, ProductID 1 , Quantity 2
    (1, 2, 1),  # OrderID 1, ProductID 2, Quantity 1
    (2, 2, 3),  # OrderID 2, ProductID 2 , Quantity 3
    (2, 3, 1),  # OrderID 2, ProductID 3 , Quantity 1
    (3, 1, 1),  # OrderID 3, ProductID 1 , Quantity 1
    (3, 3, 2)   # OrderID 3, ProductID 3 , Quantity 2
]

insert_order_details_query = '''
INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (?, ?, ?)
'''

cursor.executemany(insert_order_details_query, order_details_data)
conn.commit()

### Exercise 6: Querying Data

	•	Write a Python function that retrieves all customers who joined after a certain date.
	•	Write a Python function that retrieves all products with a price greater than a certain amount.
	•	Write a query to list all orders along with the customer’s first and last name.

Hint: Use SELECT statements with WHERE clauses and JOINs.

In [40]:
def get_customers_joined_after(date):
    conn = sqlite3.connect('ecommerce.db')
    cursor = conn.cursor()

    query = '''
    SELECT FirstName, LastName, Email, JoinDate
    FROM Customers
    WHERE JoinDate > ?
    '''
    cursor.execute(query, (date,))
    results = cursor.fetchall()

    cursor.close()
    conn.close()
    
    return results

def get_products_with_price_greater_than(price):
    conn = sqlite3.connect('ecommerce.db')
    cursor = conn.cursor()

    query = '''
    SELECT ProductName, Price, Stock
    FROM Products
    WHERE Price > ?
    '''
    cursor.execute(query, (price,))
    results = cursor.fetchall()

    cursor.close()
    conn.close()

    return results

def list_orders_with_customer_names():
    conn = sqlite3.connect('ecommerce.db')
    cursor = conn.cursor()

    query = '''
    SELECT Orders.OrderID, Customers.FirstName, Customers.LastName, Orders.OrderDate
    FROM Orders
    JOIN Customers ON Orders.CustomerID = Customers.CustomerID
    '''
    cursor.execute(query)
    results = cursor.fetchall()

    cursor.close()
    conn.close()

    return results


if __name__ == "__main__":

    date = '2023-01-01' 
    customers = get_customers_joined_after(date)
    print("Customers who joined after", date, ":", customers)

    
    price = 100.00  
    products = get_products_with_price_greater_than(price)
    print("Products with price greater than", price, ":", products)


    orders_with_customer_names = list_orders_with_customer_names()
    print("Orders with customer names:")
    for order in orders_with_customer_names:
        print(order)

Customers who joined after 2023-01-01 : [('Shakil', 'Onlil', 'shaccc@gmail.com', '2023.05.12'), ('Don', 'Donov', 'dondon@gmail.com', '2024-07-01')]
Products with price greater than 100.0 : [('Laptop', 999.99, 10), ('Smartphone', 699.99, 25), ('Headphones', 199.99, 50), ('Monitor', 249.99, 15), ('Laptop', 999.99, 10), ('Smartphone', 699.99, 25), ('Headphones', 199.99, 50), ('Monitor', 249.99, 15)]
Orders with customer names:
(1, 'Shakil', 'Onlil', '2024-10-01')
(2, 'SSkibidi', 'Toilet', '2024-10-02')
(3, 'Don', 'Donov', '2024-10-03')
(4, 'Shakil', 'Onlil', '2024-10-01')
(5, 'SSkibidi', 'Toilet', '2024-10-02')
(6, 'Don', 'Donov', '2024-10-03')

### Exercise 7: Updating Data

	•	Task: Update the stock of a product when an order is placed (decrease the Stock in Products by the quantity ordered).
	•	Write a function that updates the email address of a customer.

Hint: Use UPDATE statements and ensure data integrity.

In [41]:
def update_product_stock(product_id, quantity_ordered):
    conn = sqlite3.connect('ecommerce.db')
    cursor = conn.cursor()

    cursor.execute('SELECT Stock FROM Products WHERE ProductID = ?', (product_id,))
    result = cursor.fetchone()

    if result is None:
        print("Product not found.")
        return
    
    current_stock = result[0]

    if current_stock < quantity_ordered:
        print("Not enough stock available.")
        return


    new_stock = current_stock - quantity_ordered
    update_query = '''
    UPDATE Products
    SET Stock = ?
    WHERE ProductID = ?
    '''
    
    cursor.execute(update_query, (new_stock, product_id))
    conn.commit()
    
    print(f"Updated stock for ProductID {product_id}: New stock is {new_stock}.")

    cursor.close()
    conn.close()

def update_customer_email(customer_id, new_email):
    conn = sqlite3.connect('ecommerce.db')
    cursor = conn.cursor()

    update_query = '''
    UPDATE Customers
    SET Email = ?
    WHERE CustomerID = ?
    '''
    
    cursor.execute(update_query, (new_email, customer_id))
    conn.commit()
    
    if cursor.rowcount > 0:
        print(f"Updated email for CustomerID {customer_id} to {new_email}.")
    else:
        print("Customer not found or email was not changed.")

    cursor.close()
    conn.close()

if __name__ == "__main__":

    product_id = 1  
    quantity_ordered = 2 
    update_product_stock(product_id, quantity_ordered)


    customer_id = 1  
    new_email = 'new_email@example.com' 
    update_customer_email(customer_id, new_email)

Updated stock for ProductID 1: New stock is 8.
Updated email for CustomerID 1 to new_email@example.com.

### Exercise 8: Aggregate Functions and Grouping

	•	Write a query to find the total number of orders placed by each customer.
	•	Write a query to find the total revenue generated from all orders.

Hint: Use GROUP BY and aggregate functions like COUNT() and SUM().

In [42]:
def total_orders_per_customer():
    conn = sqlite3.connect('ecommerce.db')
    cursor = conn.cursor()

    query = '''
    SELECT Customers.FirstName, Customers.LastName, COUNT(Orders.OrderID) AS TotalOrders
    FROM Customers
    LEFT JOIN Orders ON Customers.CustomerID = Orders.CustomerID
    GROUP BY Customers.CustomerID
    '''
    
    cursor.execute(query)
    results = cursor.fetchall()

    print("Total number of orders placed by each customer:")
    for row in results:
        print(f"{row[0]} {row[1]}: {row[2]} orders")

    cursor.close()
    conn.close()

def total_revenue():
    conn = sqlite3.connect('ecommerce.db')
    cursor = conn.cursor()

    query = '''
    SELECT SUM(OrderDetails.Quantity * Products.Price) AS TotalRevenue
    FROM OrderDetails
    JOIN Products ON OrderDetails.ProductID = Products.ProductID
    JOIN Orders ON OrderDetails.OrderID = Orders.OrderID
    '''
    
    cursor.execute(query)
    total_revenue = cursor.fetchone()[0]

    if total_revenue is None:
        total_revenue = 0  # Handle case where there are no orders

    print(f"Total revenue generated from all orders: ${total_revenue:.2f}")

    cursor.close()
    conn.close()


if __name__ == "__main__":
    total_orders_per_customer()
    total_revenue()

Total number of orders placed by each customer:
Shakil Onlil: 2 orders
SSkibidi Toilet: 2 orders
Don Donov: 2 orders
Clu Wave: 0 orders
Scan Dall: 0 orders
Total revenue generated from all orders: $12799.80

### Exercise 9: Advanced Queries

	•	Write a query to list the top-selling products (products ordered most frequently).
	•	Write a query to find customers who have not placed any orders.

Hint: Use LEFT JOIN and functions like COUNT() to identify nulls.

In [44]:
def top_selling_products():
    conn = sqlite3.connect('ecommerce.db')
    cursor = conn.cursor()

    query = '''
    SELECT Products.ProductName, SUM(OrderDetails.Quantity) AS TotalSold
    FROM Products
    JOIN OrderDetails ON Products.ProductID = OrderDetails.ProductID
    GROUP BY Products.ProductID
    ORDER BY TotalSold DESC
    '''
    
    cursor.execute(query)
    results = cursor.fetchall()

    print("Top-selling products (ordered most frequently):")
    for row in results:
        print(f"{row[0]}: {row[1]} sold")

    cursor.close()
    conn.close()

def customers_without_orders():
    conn = sqlite3.connect('ecommerce.db')
    cursor = conn.cursor()

    query = '''
    SELECT Customers.FirstName, Customers.LastName
    FROM Customers
    LEFT JOIN Orders ON Customers.CustomerID = Orders.CustomerID
    WHERE Orders.OrderID IS NULL
    '''
    
    cursor.execute(query)
    results = cursor.fetchall()

    print("Customers who have not placed any orders:")
    for row in results:
        print(f"{row[0]} {row[1]}")

    cursor.close()
    conn.close()


if __name__ == "__main__":
    top_selling_products()
    customers_without_orders()

Top-selling products (ordered most frequently):
Smartphone: 8 sold
Headphones: 6 sold
Laptop: 6 sold
Customers who have not placed any orders:
Clu Wave
Scan Dall

### Exercise 10: Deleting Data

	•	Write a function to delete a customer from the database.
	•	Ensure that deleting a customer also deletes all their associated orders and order details.

Hint: Use ON DELETE CASCADE in your foreign key constraints when creating tables.

In [47]:

def create_tables():
    conn = sqlite3.connect('ecommerce.db')
    cursor = conn.cursor()


    cursor.execute('''
    CREATE TABLE IF NOT EXISTS Customers (
        CustomerID INTEGER PRIMARY KEY AUTOINCREMENT,
        FirstName TEXT,
        LastName TEXT,
        Email TEXT,
        JoinDate DATE
    )
    ''')

    cursor.execute('''
    CREATE TABLE IF NOT EXISTS Products (
        ProductID INTEGER PRIMARY KEY AUTOINCREMENT,
        ProductName TEXT,
        Price REAL,
        Stock INTEGER
    )
    ''')

    cursor.execute('''
    CREATE TABLE IF NOT EXISTS Orders (
        OrderID INTEGER PRIMARY KEY AUTOINCREMENT,
        CustomerID INTEGER,
        OrderDate DATE,
        FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID) ON DELETE CASCADE
    )
    ''')


    cursor.execute('''
    CREATE TABLE IF NOT EXISTS OrderDetails (
        OrderDetailID INTEGER PRIMARY KEY AUTOINCREMENT,
        OrderID INTEGER,
        ProductID INTEGER,
        Quantity INTEGER,
        FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE,
        FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
    )
    ''')

    conn.commit()
    cursor.close()
    conn.close()


def delete_customer(customer_id):
    conn = sqlite3.connect('ecommerce.db')
    cursor = conn.cursor()


    delete_query = '''
    DELETE FROM Customers
    WHERE CustomerID = ?
    '''

    cursor.execute(delete_query, (customer_id,))
    conn.commit()
    
    if cursor.rowcount > 0:
        print(f"Customer with ID {customer_id} has been deleted along with their associated orders and order details.")
    else:
        print(f"No customer found with ID {customer_id}.")

    cursor.close()
    conn.close()

if __name__ == "__main__":
    create_tables()
    
    customer_id_to_delete = 1  
    delete_customer(customer_id_to_delete)

No customer found with ID 1.

### Bonus Exercise: Transaction Management

	•	Implement a transaction where you:
	•	Place an order for a customer.
	•	Update the stock levels of the ordered products.
	•	If any product does not have sufficient stock, roll back the transaction.

Hint: Use BEGIN TRANSACTION, COMMIT, and ROLLBACK with exception handling in Python.

In [48]:
import sqlite3

def place_order(customer_id, product_orders):
    """
    Places an order for a customer and updates the stock levels.
    
    Parameters:
    - customer_id: The ID of the customer placing the order.
    - product_orders: A list of tuples containing (product_id, quantity).
    """
    conn = sqlite3.connect('ecommerce.db')
    cursor = conn.cursor()
    
    try:
        # Start the transaction
        conn.execute('BEGIN TRANSACTION;')

        # Check stock levels and prepare order details
        for product_id, quantity in product_orders:
            # Check if there is enough stock
            cursor.execute('SELECT Stock FROM Products WHERE ProductID = ?', (product_id,))
            stock = cursor.fetchone()
            
            if stock is None or stock[0] < quantity:
                print(f"Insufficient stock for Product ID {product_id}. Rolling back the transaction.")
                conn.rollback()  # Rollback if stock is insufficient
                return
            
            # If stock is sufficient, update stock level
            cursor.execute('UPDATE Products SET Stock = Stock - ? WHERE ProductID = ?', (quantity, product_id))

        # Insert the order into the Orders table
        cursor.execute('INSERT INTO Orders (CustomerID, OrderDate) VALUES (?, DATE("now"))', (customer_id,))
        order_id = cursor.lastrowid  # Get the ID of the new order

        # Insert order details into OrderDetails table
        for product_id, quantity in product_orders:
            cursor.execute('INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES (?, ?, ?)',
                           (order_id, product_id, quantity))

        # Commit the transaction if all operations were successful
        conn.commit()
        print(f"Order placed successfully for Customer ID {customer_id} with Order ID {order_id}.")

    except Exception as e:
        print(f"An error occurred: {e}")
        conn.rollback()  # Rollback in case of an error

    finally:
        cursor.close()
        conn.close()


if __name__ == "__main__":
    customer_id = 1  # Replace with the actual CustomerID
    product_orders = [(1, 2), (2, 1)]  # List of tuples (product_id, quantity)
    place_order(customer_id, product_orders)

Order placed successfully for Customer ID 1 with Order ID 7.

Submission: Submit your Python scripts for each exercise. Ensure your code is well-commented and follows best practices.

Notes:

	•	Exception Handling: Remember to handle exceptions and edge cases in your code to prevent crashes.
	•	Parameterized Queries: Always use parameterized queries (? placeholders) to prevent SQL injection.
	•	Closing Connections: Close your database connection after all operations are completed using connection.close().